spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 114589089071-1q0s1gsh7s8avrke208rguchvr4a1l5e.apps.googleusercontent.com
  datasource:
    url: jdbc:derby:gallery_db;create=true;collation=TERRITORY_BASED:PRIMARY

  jpa:
    database-platform: org.hibernate.dialect.DerbyTenSevenDialect
    hibernate:
      ddl-auto: update
  #  properties:
  #    javax:
  #      persistence:
  #        schema-generation:
  #          create-source: metadata
  #          scripts:
  #            action: create
  #            create-target: ddl.sql

server:
  port: 18181
  servlet:
    context-path: /gallery
